events { worker_connections 1024; }

http {
    log_format main_custom '$remote_addr - $remote_user [$time_local] "$request" '
                           '$status $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main_custom;
    error_log  /var/log/nginx/error.log warn;

    include /etc/nginx/conf.d/blacklist.conf;

    # LA SOLUCIÓN: Usar el DNS interno de Docker (127.0.0.11)
    # Esto busca dinámicamente tus contenedores sin perder la conexión
    resolver 127.0.0.11 valid=5s;

    server {
        listen 3000;

        # Captura las rutas de la app (ej. /api/districts, /api/telemetry)
        location / {
            # Usamos una variable para forzar a Nginx a re-resolver la IP con el DNS de Docker
            set $backend_upstream http://eg-backend:3000;
            proxy_pass $backend_upstream;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Tiempos de espera por si tu backend está procesando mucha telemetría
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}