events { 
    worker_connections 1024; 
}

http {
    # 1. CONFIGURACIÓN DE LOGS (Requerido por Fail2ban para detectar ataques)
    log_format main_custom '$remote_addr - $remote_user [$time_local] "$request" '
                           '$status $body_bytes_sent "$http_referer" '
                           '"$http_user_agent" "$http_x_forwarded_for"';

    access_log /var/log/nginx/access.log main_custom;
    error_log  /var/log/nginx/error.log warn;

    # 2. SEGURIDAD Y RESOLUCIÓN DINÁMICA
    # Bloqueo de IPs inyectado por Fail2ban
    include /etc/nginx/conf.d/blacklist.con[f];

    # DNS interno de Docker. Fuerza a Nginx a re-consultar las IPs de los 
    # contenedores de forma dinámica cada 5 segundos (vital para el escalado).
    resolver 127.0.0.11 valid=5s;

    # 3. GATEWAY / PROXY REVERSO (Puerto 3000)
    server {
        listen 3000;

        # --- MÓDULO A: MICROSERVICIO DE AUTENTICACIÓN ---
        # Captura todo lo que vaya a /api/auth/ (ej: /api/auth/login)
        location /api/auth/ {
            # Usamos variable para que el resolver de Docker busque eg-auth-service dinámicamente
            set $auth_upstream http://eg-auth-service:3001;
            proxy_pass $auth_upstream;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # Tiempos de espera estándar para auth
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }

        # --- MÓDULO B: BACKEND PRINCIPAL (Telemetría, Distritos, Hora Pico) ---
        # Ruta por defecto para todo lo demás
        location / {
            # Usamos variable para forzar el balanceo dinámico de Docker entre las réplicas escaladas
            set $backend_upstream http://eg-backend:3000;
            proxy_pass $backend_upstream;
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            
            # Tiempos de espera optimizados para ráfagas pesadas de telemetría IoT
            proxy_connect_timeout 5s;
            proxy_read_timeout 10s;
        }
    }
}