dbdir /var/lib/munin
htmldir /var/lib/munin/www
logdir /var/log/munin
rundir /var/run/munin

tmpldir /etc/munin/templates

graph_strategy cron

[localhost]
    address 127.0.0.1
    use_node_name yes
