[DEFAULT]
banaction = dummy
logtarget = /var/log/fail2ban/fail2ban.log

[api-protection]
enabled  = true
filter   = api-filter
logpath  = /var/log/nginx/access.log
maxretry = 10
findtime = 600
bantime  = 3600
action   = %(banaction)s